seed: 18591845184
#seed: 97763026622289

run_name: bead_crossing
n_dim: 2
n_periodic: 2
delta: 0.01
n_steps: 800000000
boundary: 0
n_update_cells: -1
cell_length: 1
movie_flag: 1

graph_flag: 1
n_graph: 100
graph_background: 0
print_complete: 0

system_radius: 10
potential: soft
soft_potential_mag: 8.59410
like_like_interactions: 1
stoch_flag: 0
f_cutoff: 10000
n_thermo: 100
thermo_flag: 1
local_order_analysis: 0
local_order_bin_width: 0.5
local_order_width: 40
local_order_average: 1
interaction_flag: 1
overlap_analysis: 0
density_analysis: 0
density_com_only: 0
density_bin_width: 0.1

centrosome:
  num: 0
  n_filaments_min: 1
  n_filaments_max: 1
  alignment_potential: 1
  k_align: 1000
  checkpoint_flag: 1

filament:
  num: 0
  packing_fraction: -1
  overlap: 0
  insertion_type: custom
  insert_file: filament_crossing.yaml
  diameter: 1
  length: 10
  perlen_ratio: 1000
  #intrinsic_curvature: .0628
  n_bonds: 3
  driving_factor: 3
  n_spec: 1000
  n_checkpoint: 100
  spec_flag: 1
  checkpoint_flag: 1
  flagella_flag: 0
  flagella_freq: 0.1
  flagella_period: 2
  flagella_amplitude: 3

br_bead:
  num: 1
  diameter: 1
  driving_factor: 30
  insertion_type: custom
  insert_file: bead_crossing.yaml

passive_filament:
  num: 1
  diameter: 1
  length: 10
  draw_type: bw
  insertion_type: custom
  insert_file: bead_crossing.yaml
  perlen_ratio: 100 
  n_bonds: 3
  posit_flag: 0
  spec_flag: 0
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100


