FROM debian:10.2-slim
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends \
        build-essential \
        ca-certificates \
        vim \
        git \
        cmake \
        wget \
        curl \
        htop \
        pkg-config \
        doxygen \
        libyaml-cpp-dev \
        libgsl-dev \
        libfftw3-dev \
        libopenmpi-dev \
        libboost-math1.67-dev &&\
    rm -rf ~/.cache
