FROM ubuntu:bionic

WORKDIR /build

RUN apt-get -qq update && apt-get install -qqy --no-install-recommends \
        build-essential \
        ca-certificates \
        vim \
        cmake \
        wget \
        git \
        curl \
        htop \
        pkg-config \
        doxygen \
        libgsl-dev \
        libfftw3-dev \
        libopenmpi-dev &&\
    rm -rf ~/.cache

RUN wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz &&\
    mkdir -p /usr/include/boost &&\
    tar -xzf boost_1_67_0.tar.gz -C /usr/include/boost --strip-components=2

RUN wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.0.tar.gz &&\
    tar -xzf yaml-cpp-0.6.0.tar.gz &&\
    cd yaml-cpp-yaml-cpp-0.6.0 &&\
    mkdir build && cd build && cmake .. && make -j4  && make install

RUN git clone --recursive --single-branch --branch master https://github.com/jeffmm/simcore.git &&\
    cd simcore &&\
    ./install.sh -tI

RUN rm -rf /build
WORKDIR /mnt
ENTRYPOINT []
