// system_parameters defaults

  seed = 7859459105545; // seed for random number generator
  n_dim = 3;
  n_periodic = 0;
  boundary_type = 0;
  insert_type = 0; 
  n_filaments_free = 1;
  n_filaments_attached = 0;
  n_spheres = 0;
  n_particles = 0;
  particle_radius = 1;
  particle_mass = 1;
  n_steps = 100000000;
  n_graph = 10; // number of frames between refreshing graphics
  dynamic_instability_flag = 1;
  force_induced_catastrophe_flag = 1;
  error_analysis_flag = 0;
  graph_flag = 1; 
  grab_flag = 0;
  pair_interaction_flag = 1;
  theta_validation_flag = 0;
  buckling_analysis_flag = 0;
  time_analysis_flag = 0;
  save_state_flag = 0;
  n_save_state = 100000;
  n_bins = 1000;
  n_validate = 10000;
  n_buckle_on = 1000000;
  n_buckle_off = 1000000;
  metric_forces = 1;
  delta = 0.001; // time duration between each simulation step
  friction_ratio = 2;
  mother_daughter_dist = 680; // distance between mother-daughter cell centers
  mother_radius = 400; // radius of mother cell
  daughter_radius = 300; // radius of daughter cell
  sphere_radius = 50; // radius of spindle blob
  filament_diameter = 1; // diameter of microtubule
  min_length = 10;
  max_length = 1000;
  min_segment_length = 3;
  max_segment_length = 5;
  persistence_length = 5000; 
  spring_filament_sphere = 80; // spring constant for sb-mt attachment interaction
  spring_buckling_init = 0;
  buckle_rate = 0.001;
  buckle_parameter = 0.90;
  r_cutoff_sphere = 1.1225; 
  r_cutoff_boundary = 1.1225;
  f_shrink_to_grow = 0; // Frequencies for dynamic instability
  f_shrink_to_pause = 0.01;
  f_pause_to_grow = 0.01;
  f_pause_to_shrink = 0.01;
  f_grow_to_pause = 0.01;
  f_grow_to_shrink = 0;
  v_poly = 0.01;
  v_depoly = 0.02;
  graph_diameter = 1;
  grab_file = 0;
  cell_list_flag = 0;
  
