#ifndef _SIMCORE_PARAMETERS_H_
#define _SIMCORE_PARAMETERS_H_

// parameters.h, generated automatically using make_params

struct system_parameters {

  int n_filaments_attached = 0;
  int n_spheres = 0;
  int n_particles = 0;
  double particle_radius = 1;
  long seed = 7859459105545;
  int n_dim = 3;
  double system_radius = 400;
  int n_periodic = 0;
  int boundary_type = 0;
  int insert_type = 0;
  int n_filaments_free = 1;
  double lj_epsilon = 1;
  double particle_mass = 1;
  int n_steps = 100000000;
  int n_graph = 1000;
  int dynamic_instability_flag = 1;
  double bud_height = 680;
  int force_induced_catastrophe_flag = 1;
  int graph_flag = 0;
  int error_analysis_flag = 0;
  int grab_flag = 0;
  int theta_validation_flag = 0;
  int pair_interaction_flag = 1;
  int n_save_state = 100000;
  int buckling_analysis_flag = 0;
  int time_flag = 0;
  int save_state_flag = 0;
  int n_bins = 1000;
  double bud_radius = 300;
  int n_validate = 10000;
  int n_buckle_on = 1000000;
  int n_buckle_off = 1000000;
  int metric_forces = 1;
  double delta = 0.001;
  double friction_ratio = 2;
  double sphere_radius = 50;
  double filament_diameter = 1;
  double min_segment_length = 3;
  double max_rod_length = 1000;
  double min_rod_length = 2;
  double buckle_rate = 0.001;
  double buckle_parameter = 0.90;
  double max_segment_length = 5;
  double persistence_length = 5000;
  double spring_filament_sphere = 80;
  double spring_buckling_init = 0;
  double f_shrink_to_grow = 0.017;
  double r_cutoff_sphere = 1.1225;
  double r_cutoff_boundary = 1.1225;
  double v_depoly = 0.793;
  double f_pause_to_grow = 0.0;
  double f_shrink_to_pause = 0.0;
  double f_pause_to_shrink = 0.0;
  double f_grow_to_pause = 0.0;
  double v_poly = 0.44;
  double f_grow_to_shrink = 0.00554;
  char *grab_file;
  double graph_diameter = 0;
  int cell_list_flag = 0;
  int rigid_tether_flag = 0;
  int rod_diffusion = 1;
  int position_correlation_flag = 0;
  int graph_background = 1;
  int n_br_bead = 0;
  double br_bead_diameter = 1;
  int n_xlink = 0;
  double xlink_diameter = 1;
  double md_bead_diameter = 1;
  int n_md_bead = 0;
  double md_bead_mass = 1;
  double cell_length = 10;
  double wca_eps = 1;
  int n_update_cells = 10;
  int energy_analysis_flag = 0;
  double f_cutoff = 100;
  double wca_sig = 1;
  int n_rod = 0;
  double rod_length = 3;
  double rod_diameter = 1;
  int rod_fixed = 0;
  double driving_factor = 0;
  char *potfile;
  int tracking_type = 2;
  int draw_interactions = 0;
  double masterskin = 1.0;
  int max_overlap = 100000;
  char *kmcfile;
  char *config_file;
  double gamma_ratio = 2;
  int n_filament = 0;
  int posit_flag = 0;
  int n_posit = 100;
  int diffusion_validation_flag = 0;
  int n_md_bead_opt = 100;
  int diffusion_analysis = 0;
  double max_child_length = 3;
  char *datafile;
  int avg_posits = 0;
  int diffusion_interval = 1000;
  double target_pressure = 100;
  int filament_analysis = 0;
  int virial_time_avg = 100;
  int constant_pressure = 0;

};

#endif // _SIMCORE_PARAMETERS_H_